SELECT :schema AS OWNER,
       c.TABLE_NAME,
       c.COLUMN_NAME,
       com.COMMENTS,
       c.COLUMN_ID,
       c.DATA_TYPE
FROM USER_TAB_COLUMNS c
LEFT JOIN USER_COL_COMMENTS com
       ON c.TABLE_NAME = com.TABLE_NAME
      AND c.COLUMN_NAME = com.COLUMN_NAME
WHERE EXISTS (
    SELECT 1
      FROM USER_TAB_COLUMNS t
     WHERE t.TABLE_NAME = c.TABLE_NAME
       AND t.COLUMN_NAME = :target_column
)
  AND EXISTS (
    SELECT 1
      FROM USER_TABLES u
     WHERE u.TABLE_NAME = c.TABLE_NAME
)
ORDER BY c.TABLE_NAME, c.COLUMN_ID
