SELECT acc.OWNER,
       acc.TABLE_NAME,
       acc.COLUMN_NAME,
       acc.POSITION
FROM USER_CONS_COLUMNS acc
JOIN USER_CONSTRAINTS ac
  ON acc.OWNER = ac.OWNER
 AND acc.CONSTRAINT_NAME = ac.CONSTRAINT_NAME
WHERE ac.CONSTRAINT_TYPE = 'P'
  AND acc.OWNER = :schema
ORDER BY acc.OWNER, acc.TABLE_NAME, acc.POSITION
